window.alert("Ola sou uma IA quero fazer algumas perguntas...")
window.confirm("Voce esta preparado?")
window.prompt("Qual seu nome?")
window.alert("Interessante")
window.prompt("Gosta de fazer o que?")
window.alert("Que legal.")
window.prompt("Voce e de qual regiao?")
window.alert("Eu tambem sou da mesma regiao que voce =)")
window.prompt("Qual seu prato preferido?")
window.prompt("uaaauu")