window.alert("Ola sou uma IA quero fazer algumas perguntas...")
window.confirm("Voce esta preparado?")
var nome = window.prompt("Qual seu nome?")
window.alert("Interessante " + nome)
window.alert("Seu nome tem " + nome.length + " letras")
window.alert("Seu nome em letras maiusculas " + nome.toUpperCase() )
window.alert("Seu nome em letras minuscula " + nome.toLowerCase() )
window.prompt("Gosta de fazer o que?")
window.alert("Que legal.")
var region = window.prompt("Voce e de qual regiao?")
window.alert("Eu tambem sou de " + region + " =)" )
window.prompt("Qual seu prato preferido?")
window.prompt("uaaauu")